name: itdat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  google_fonts: ^6.2.1
  lottie: ^3.3.0
  vibration: ^2.0.1
  http: ^1.2.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  qr_flutter: ^4.1.0
  app_settings: ^5.1.1
  nfc_manager: ^3.5.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  provider: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  webview_flutter: ^4.2.1
  google_sign_in: ^5.4.0
  kakao_flutter_sdk: ^1.9.6
  flutter_naver_login: ^2.0.0
  firebase_auth: ^4.4.0
  uuid: ^3.0.6
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logowhite.png
    - assets/logoblack.png
    - assets/nfcAnime.json
    - assets/nfc.png
    - assets/qr.png